#!/bin/sh
parse_git_tracker_and_ticket() {
  git symbolic-ref --short HEAD | grep -e '[A-Z]\+-[0-9]\+' -o
}

MESSAGE="$(cat $1)"
TICKET=$(parse_git_tracker_and_ticket)

if [ -n "$TICKET" ]
then
   echo "$TICKET $MESSAGE" > $1
fi
